---
# file: roles/common/tasks/ssh.yaml

- name: change firewall to open non-standard ssh port on public zone
  firewalld: port={{ansible_ssh_port}}/tcp state=enabled permanent=true immediate=true zone=public

- name: configure sshd
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart sshd

- meta: flush_handlers

- name: change firewall to close standard ssh port on public zone
  firewalld: service=ssh state=disabled permanent=true immediate=true zone=public

- name: change firewall to close standard ssh port on internal zone
  firewalld: service=ssh state=disabled permanent=true immediate=true zone=internal
